final:
	(cd endians; make final)
	(cd grep; make final)
	(cd static; make final)
	(cd extern; make final)
	(cd rm_comment; make final)
	(cd str_func; make final)
clean:
	(cd endians; make clean)
	(cd grep; make clean)
	(cd static; make clean)
	(cd extern; make clean)
	(cd rm_comment; make clean)
	(cd str_func; make clean)

